### ISSUE TITLE
Suggestion for plugin development

### ISSUE THREAD

**Issue by secfb** [vaycore/OneScan#10]
The car was really nice and useful. This plugin really works great.  Can you add the following wordlists to make this tool better? Especially if the parameters in top25-parameter are imported to the application, very good vulnerabilities can be detected.

**Comment by vaycore** [comment]
> The car was really nice and useful. This plugin really works great. Can you add the following wordlists to make this tool better? Especially if the parameters in top25-parameter are imported to the application, very good vulnerabilities can be detected.

Thank you for choosing the OneScan plugins. You can add wordlists according to your habits, in the `~/.config/OneScan/wordlist` directory.
