### ISSUE TITLE
建议来个控制递归层数

### ISSUE THREAD

**Issue by Monster-24** [vaycore/OneScan#12]
能否设置个控制递归的层数，一旦目录有八层之多，那不是要递归遍历很多次，这容易引发waf，一般递归2-3层就可以了

**Comment by vaycore** [comment]
新发布的 `1.2.0` 版本已实现该功能。可前往 `Config` -> `Request` 页面配置：

![image](https://github.com/vaycore/OneScan/assets/25676623/dcc375c6-c081-4023-b05f-a0e95e49a823)
