### ISSUE TITLE
[特性] 支持相对路径的配置文件

### ISSUE THREAD

**Issue by peter5he1by** [vaycore/OneScan#16]
能否按优先级读取配置文件，如：

    %USERPROFILE%\.config\OneScan
    插件jar包所在目录\.config\OneScan

以支持便携的burpsuite部署。(因为有的渗透或者红队要在vdi部署环境）

**Comment by vaycore** [comment]
感谢您的建议，目前已发布 OneScan 1.3.7 版本。插件将优先检测当前插件 jar 包所在目录下是否存在 `OneScan` 目录，如果存在，将使用该目录作为工作目录；否则，使用如下路径作为工作目录

```text
linux、macOS：
~/.config/OneScan/

windows：
C:\Users\<用户名>\.config\OneScan\
```

**Comment by peter5he1by** [comment]
感谢开发者的努力！

**Comment by peter5he1by** [comment]
![图片](https://github.com/vaycore/OneScan/assets/86906331/7e88b1e8-3fc5-4973-a8a6-8825457a938c)

从图上这个方法进去之后，hasKey判断返回的是true，于是这里这个方法没有修改wordlist的路径，配置文件目录仍然使用的是homedir\.config\OneScan目录，建议把配置目录功能抽到一个类，引用太分散了改bug也不容易。

**Comment by vaycore** [comment]
> ![图片](https://user-images.githubusercontent.com/86906331/278958203-7e88b1e8-3fc5-4973-a8a6-8825457a938c.png)
> 
> 从图上这个方法进去之后，hasKey判断返回的是true，于是这里这个方法没有修改wordlist的路径，配置文件目录仍然使用的是homedir.config\OneScan目录，建议把配置目录功能抽到一个类，引用太分散了改bug也不容易。

关于 `wordlist` 路径，在您迁移目录后，可以在 Config -> Other -> Wordlist Directory 中配置您的新路径。或者直接在配置文件修改即可

**Comment by peter5he1by** [comment]
好的感谢，原来是这样，我对这个插件还不是很熟练，抱歉打扰~

**Comment by peter5he1by** [comment]
所以配置文件里的wordlist路径需要绝对路径，是否可以考虑优化下，与配置目录便携功能相关联；

1. 比如引入%OneScanProfileDir%变量替换之类的？
2. 或者给一个默认相对路径的wordlist（相对于当前配置目录），这样在config.json里面不配置dict-path就表明使用默认值？

**Comment by vaycore** [comment]
实际上是支持相对路径的（需要在配置文件中修改），只不过是以 BurpSuite.jar 目录作为当前 jar 包所在目录

**Comment by peter5he1by** [comment]
问君能有几多愁，恰似一江春水向东流。

**Comment by peter5he1by** [comment]
如果可以的话还是把配置目录统一成一个比较好，或者config.json里的key使用默认值的时候不要保存到配置文件里，否则插件加载后config.json里的几个目录配置就固定了，没法便携。
