### ISSUE TITLE
规则匹配限制英文，能否加上中文

### ISSUE THREAD

**Issue by beijing-university** [vaycore/OneScan#18]

**Comment by vaycore** [comment]
请问是哪里的规则匹配？

**Comment by beijing-university** [comment]
我的问题，抱歉。dashboard可以用

**Comment by beijing-university** [comment]
不过匹配的这个分词可能有点问题，是否给上部分匹配的支持
![image](https://github.com/vaycore/OneScan/assets/36041172/608d46a7-fc39-448c-942c-ee51a9e1aa83)
![image](https://github.com/vaycore/OneScan/assets/36041172/b30ac13c-93c6-4b68-898e-55f29f8dbebc)

**Comment by vaycore** [comment]
使用等于条件匹配时，与填写的内容完全相等才会匹配，肯定无法过滤。你可以尝试使用 `包含`、`不包含` 等条件匹配关键字
