### ISSUE TITLE
load error！

### ISSUE THREAD

**Issue by Xiaosesh** [vaycore/OneScan#19]
outout：java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "rulesMap" is null

The Markinfo&Onescan plugin is also not visible in the response package!

**Comment by vaycore** [comment]
Based on the exception information you provided, it was found that this is not a problem with OneScan plug-in. Please check if your HaE plug-in configuration is normal

> Or, update your HaE plugin to the latest version
