### ISSUE TITLE
动态变量添加目录地址

### ISSUE THREAD

**Issue by lml20000827** [vaycore/OneScan#21]
比如
https://github.com/vaycore/OneScan/issues/new
这个url中，添加new作为动态变量，我遇到过几次是目录作为备份文件名，从而泄露的

**Comment by vaycore** [comment]
如果结尾是 `/` 斜杠呢？ 例如：https://github.com/vaycore/OneScan/issues/new/

**Comment by lml20000827** [comment]
如果以/结尾，找最后一级目录做动态变量
我统计了一下我发现过的备份文件泄露
http://x.x.x.x/FaWu/loginUat.htm --> http://x.x.x.x/FaWu/FaWu.zip
http://x.x.x.x/InternaTalentMarketH5/index  -->http://x.x.x.x/InternaTalentMarketH5.zip
https://github.com/vaycore/OneScan/issues/new  -->https://github.com/vaycore/OneScan/issues/new.zip
以一级目录作为文件名次数多，最后一级目录遇到的情况最少

**Comment by lml20000827** [comment]
如果以/结尾，找最后一级目录做动态变量
我统计了一下我发现过的备份文件泄露
http://x.x.x.x/FaWu/loginUat.htm --> http://x.x.x.x/FaWu/FaWu.zip
http://x.x.x.x/InternaTalentMarketH5/index  -->http://x.x.x.x/InternaTalentMarketH5.zip
https://github.com/vaycore/OneScan/issues/new  -->https://github.com/vaycore/OneScan/issues/new.zip
以一级目录作为文件名次数多，最后一级目录遇到的情况最少

**Comment by vaycore** [comment]
既然这样，那是不是最后一级目录的动态变量就不用加了😂

**Comment by lml20000827** [comment]
可以，好像当时最后一级目录当文件名的备份文件用dirsearch通用字典扫出来的。可以考虑把一级目录加入动态变量 中

**Comment by vaycore** [comment]
一级目录动态变量 `{{webroot}}` 已经有了，是 One 哥当时提出要加的。详细可参考文档：[动态变量](https://github.com/vaycore/OneScan?tab=readme-ov-file#%E5%8A%A8%E6%80%81%E5%8F%98%E9%87%8F)
