### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by JDXN** [vaycore/OneScan#22]
师傅，你好：
我用了这个工具，感觉还挺好用的，这里提几点优化建议，望师傅采纳~
     1、建议dashboard面板里，在对应列能将此列对应值作为筛选条件，选择与或非等逻辑并入过滤器中，这样方便操作过滤器【比如我想查看Length!=4000的和Length!=6000的】【目前只能通过filter手动输入添加，稍显麻烦，而且同样的列名，居然不能进行多次组合筛选，建议至少要将这个bug给改掉】
     
     最后，感谢师傅的坚持付出，respect !~

**Comment by vaycore** [comment]
首先，非常感谢您提出的建议。经过考虑后，对您的建议作出如下回应：

1. 将筛选放在右键菜单进行过滤，不会比直接在过滤器中调整方便很多（可调整的选项太多了）
2. 一般过滤规则相对来说比较固定，不会经常变动（至少我在使用过程中是这样的），要调整也是针对站点调整，也不会太麻烦吧？
3. 同样的列名，是可以通过 `Add filter` 按钮添加多条规则来组合筛选的（如果我理解有误，欢迎补充）
4. 如果您坚决需要优化，可尝试自行定制对应功能的代码（插件中的代码注释也还算完整）

再次感谢您提出的建议，谢谢！
