### ISSUE TITLE
发现扫描只扫描了GET请求，并没有扫描到POST请求

### ISSUE THREAD

**Issue by jielansudo** [vaycore/OneScan#24]
这个地方是这样，还是需要怎么设置吗

![image](https://github.com/vaycore/OneScan/assets/50390082/0add61fd-0d3d-48bb-8b7c-22b59a00fdc2)

**Comment by vaycore** [comment]
目录扫描只使用 GET 请求。如果要追加扫描 POST 请求，可通过配置 Payload Processing 实现。例如：
![image](https://github.com/vaycore/OneScan/assets/25676623/ed4138de-588a-4215-91c8-833a44fd4844)

**Comment by jielansudo** [comment]
我可以针对某个目录进行post请求吗，就是不针对所有的目录

**Comment by vaycore** [comment]
这个不可以
