### ISSUE TITLE
临时添加过滤

### ISSUE THREAD

**Issue by sdfdfasd12** [vaycore/OneScan#26]
![image](https://github.com/vaycore/OneScan/assets/144324900/a0b41e60-7368-4e03-bc0e-11f6ac3452f4)

可以添加一个临时过滤方法吗，如：Length 相同太多，临时过滤(防止添加永久过滤漏掉相同重要的数据)

**Comment by vaycore** [comment]
1.6.11 版本已发布，已新增临时过滤功能
