### ISSUE TITLE
建议添加个超时参数

### ISSUE THREAD

**Issue by Tears-of-the-sun** [vaycore/OneScan#27]
扫描时如果被封禁了或者不可达了会导致队列大量等待，造成拥堵

**Comment by vaycore** [comment]
由于 OneScan 在扫描时是调用 BurpSuite 提供的接口进行网络请求，这种请求方式无法定义超时参数，所以需要自行在 BurpSuite 设置页面配置所需的超时时间：

![image](https://github.com/vaycore/OneScan/assets/25676623/0bb3d520-4a11-47ba-b4b3-e8a2c645b5c2)

另外，请求失败的数据，会在列表中显示状态码为 `-1` 值（前提是没有过滤），并不会造成拥堵。示例如下：

![image](https://github.com/vaycore/OneScan/assets/25676623/4ea3b1e6-c4c4-4b82-8c5e-cb5cf7839bf1)

感谢您提供的建议

**Comment by Tears-of-the-sun** [comment]
好的，造成拥堵那里应该是我没表述清楚
在设置qps大于1的情况下，扫描已死/不开或者刚刚被ban的站点，扫描队列很缓慢看着就像单队列扫描一样，但是扫描存活的站点速率就是正常的

**Comment by vaycore** [comment]
这种情况很正常，扫描任务占满了线程，或者达到了 QPS 限制，那只能排队等待前面的任务执行完成

**Comment by vaycore** [comment]
抱歉，我重新理清了一下。那里是我的回答有问题，确实会造成拥堵😅。这期间可以继续等待前面的任务执行完成，也可以点击 Stop 停止所有任务

**Comment by Tears-of-the-sun** [comment]
没法解决吗，等待的时间确实太长了，卡排队再停掉，后续队列不就丢失了么

**Comment by vaycore** [comment]
可以参考前面说的 Burp 的请求超时设置。或者你可以下载源码自行定制 OneScan 插件，通过引入第三方的请求库，单独设置请求超时的时间

**Comment by Tears-of-the-sun** [comment]
超时能理解，因为超时导致后续队列全部像单线程那样卡住也没法解决是吧

**Comment by vaycore** [comment]
确实，无法解决因响应超时导致的扫描任务执行缓慢的问题
