### ISSUE TITLE
请求头会出现X-Forwarded-For: XXX这类的信息？

### ISSUE THREAD

**Issue by chiputaohuibianbai** [vaycore/OneScan#28]
显示如果是绿色，请求包会有这种ip信息X-Forwarded-For: 172.24.4.64
但是正式请求包里面没有IP，比较奇怪，这个是什么功能呢？有交流群嘛？

**Comment by vaycore** [comment]
在 `Config -> Request -> Header` 中可以定义请求头信息：

![image](https://github.com/vaycore/OneScan/assets/25676623/b452b029-fc5a-4fee-95d6-b40f03b08764)

或者可以关闭 `Databoard -> Replace Header` 选项：

![image](https://github.com/vaycore/OneScan/assets/25676623/128fbe5e-4e41-4b89-b38f-5772cae2db47)

该功能主要是用于 Bypass 某些站点无法访问的情况。交流群在说明文档最下面：

![image](https://github.com/vaycore/OneScan/assets/25676623/e5842960-db9e-4609-8bf4-23f6d3bc8270)

感谢您的问题反馈
