### ISSUE TITLE
建议设置一个参数，超过该数据长度的大长度数据不直接预览或者需要二次确认

### ISSUE THREAD

**Issue by Tears-of-the-sun** [vaycore/OneScan#29]
备份文件太大一点开就释怀得死掉了

<img width="371" alt="屏幕截图 2024-07-02 093919" src="https://github.com/vaycore/OneScan/assets/82652017/4d30b819-04ce-47ca-b30b-d9492fbf6648">

**Comment by vaycore** [comment]
1.6.11 版本已发布，新增配置项：限制请求、响应包最大显示长度。可在 `Other` -> `Maximum display length` 进行配置
