### ISSUE TITLE
希望能增加选项，主动配置是否启用非递归扫描的模块

### ISSUE THREAD

**Issue by winezer0** [vaycore/OneScan#30]
希望能增加选项，主动配置是否启用非递归扫描的模块UI 【如 FingerPrint Collect HAE】

以及 消息编辑框的参数提示功能

**Comment by vaycore** [comment]
能否描述更详细一些

**Comment by winezer0** [comment]
因为我的需求是【递归目录扫描】，因为我还使用了【CaA、FingerPrint】等插件，导致功能重复了，
希望就是增加几个可选框，能够把这额外的功能关闭掉，不在ui中和消息框中调用。

**Comment by vaycore** [comment]
感谢你提供的意见，我大概懂你意思了。经过考虑，OneScan 不予采纳该建议。不过你可自行下载源代码删改，具体相关代码如下：

1. `BurpExtender` 类的 `initData` 方法（代码 `105` 行），删除该行后，消息框中将不再调用相关模块：

![image](https://github.com/vaycore/OneScan/assets/25676623/e38eb527-9005-4947-9351-d13bb47297b8)

2. `FpManager` 类的 `check` 方法（代码 `121` 行），可删除所有调用该方法的代码，或者直接按如下方式直接 `return` 即可：

![image](https://github.com/vaycore/OneScan/assets/25676623/10bc22c9-8a74-466b-9860-610f26879e7d)

3. `CollectManager` 类的 `collect` 方法（代码 `115` 行），与指纹（Fingerprint）模块类似：

![image](https://github.com/vaycore/OneScan/assets/25676623/8db3b877-4ddc-4881-8f1d-c0e8b7ad6a5e)

4. 如果希望删除 Fingerprint、Collect 标签页，可删除如下代码：

![image](https://github.com/vaycore/OneScan/assets/25676623/ed310c36-c5ba-4c4e-a1b9-c40b812a666a)

再次感谢你提供的意见
