### ISSUE TITLE
【功能建议】希望在辅助面板增加 HaE 匹配结果的标签栏

### ISSUE THREAD

**Issue by kenyon-wong** [vaycore/OneScan#32]
OneScan 版本：

OneScan v1.6.11

希望在辅助面板增加显示 HaE 的匹配结果，目前只显示 Fingerprint 和 json的结果，不太方便

![onescan_info](https://github.com/user-attachments/assets/27ef2605-c686-410c-b4fc-a59fc71b1669)

**Comment by vaycore** [comment]
非常感谢你提供的建议。设计在 `OneScan` 插件中安装 `HaE` 仅仅用于 `Databoard` 提取并展示高亮数据（作用域也只限于 `OneScan` 中），方便快速定位敏感信息。如按照建议进行修改，会导致和 `BurpSuite` 的 `HaE` 插件冲突，产生显示异常等问题。如需全局使用 `HaE` 的匹配结果，请在 `BurpSuite` 中安装 `HaE` 插件
