### ISSUE TITLE
配置hae时出现错误

### ISSUE THREAD

**Issue by hunzhigewu** [vaycore/OneScan#33]
![image](https://github.com/user-attachments/assets/059834dd-f3ad-4572-a47e-0b7bc6c2a78b)
如图所示

**Comment by vaycore** [comment]
感谢您的反馈，OneScan 1.7.0 已兼容 HaE 4.0 版本，目前还在测试中，敬请期待。

**Comment by vaycore** [comment]
已发布 OneScan 1.7.0 版本，欢迎师傅安装体验。
