### ISSUE TITLE
关于功能的一些建议

### ISSUE THREAD

**Issue by able9527** [vaycore/OneScan#4]
师傅好
最近有用这个插件，个人感觉挺不错的，但是关于功能还有些建议：
1、关于数据面板优化，可以只显示200（或者用户自定义选择）状态码的路径，毕竟层层路由拼接，有就是有，没有就是没有，状态码太多干扰视线。
2、有些站点200状态码也会返回很多响应长度一样的路径，可以添加个过滤功能用户自定义一个阈值，比如超过3个或者5个包的返回长度一样的路径后续该长度的响应直接丢弃不再显示。
3、重复的域名再次访问时可直接跳过，误触之前检测过的站又会检测一遍，数据面板就会有很多没必要的冗余
最后再麻烦问下师傅{{domain.main}}、{{domain.name}}变量是在payload里面用的吗还是其它地方，有无实际利用场景比如说？

**Comment by vaycore** [comment]
> 师傅好 最近有用这个插件，个人感觉挺不错的，但是关于功能还有些建议： 1、关于数据面板优化，可以只显示200（或者用户自定义选择）状态码的路径，毕竟层层路由拼接，有就是有，没有就是没有，状态码太多干扰视线。 2、有些站点200状态码也会返回很多响应长度一样的路径，可以添加个过滤功能用户自定义一个阈值，比如超过3个或者5个包的返回长度一样的路径后续该长度的响应直接丢弃不再显示。 3、重复的域名再次访问时可直接跳过，误触之前检测过的站又会检测一遍，数据面板就会有很多没必要的冗余 最后再麻烦问下师傅{{domain.main}}、{{domain.name}}变量是在payload里面用的吗还是其它地方，有无实际利用场景比如说？

功能建议已知悉。{{domain}}、{{domain.main}}、{{domain.name}} 设计是用于备份文件探测，以及自定义请求头时填充动态的请求信息；动态变量只在 Payload 和 Header 配置中生效

**Comment by vaycore** [comment]
0.5.2 版本已发布，主要新增过滤器功能。关于第3条去重建议不予采纳，因为原先版本已支持去重功能，当“清空所有记录”时，会重置去重列表。
