### ISSUE TITLE
关于Payload Processing 

### ISSUE THREAD

**Issue by kingz40o** [vaycore/OneScan#5]
比如设置了Payload Processing 选项，默认是对payload进行规则处理后扫描，原始payload不会进行扫描，是否可以增加选择扫描两者

**Comment by vaycore** [comment]
久等了，新发布的 `1.2.0` 版本已实现该功能。可通过关闭 `Merge Payload Processing` 实现扫描两者：

![image](https://github.com/vaycore/OneScan/assets/25676623/914c542d-0097-41dc-9f28-ab2916935647)
