### ISSUE TITLE
黑名单问题

### ISSUE THREAD

**Issue by zhiao6** [vaycore/OneScan#8]
我记得之前的版本是只输入根域名就可以排除所有该域名的请求，现在需要单独输入每个子域名才可以
是功能的需求吗

**Comment by vaycore** [comment]
> 我记得之前的版本是只输入根域名就可以排除所有该域名的请求，现在需要单独输入每个子域名才可以 是功能的需求吗

新版本添加了 `*` 通配符；如果不加通配符的话，域名需要完全匹配才会拦截。
